const dataProducts = [
    {
        id: 1,
        name: "Llave de Cofre de Suministros de Mann Co.",
        img: "https://wiki.teamfortress.com/w/images/8/83/Backpack_Mann_Co._Supply_Crate_Key.png",
        type: "Herramienta",
        price: 100,
        description: "Se usa para abrir Cofres de Suministros de Mann Co. cerrados.",
        stock: 10,
        use: 1,
        categoryId: 1,
        initial: 1,
    },
    {
        id: 2,
        name: "Series de Cofres De Suministros Mann Co. #1",
        img: "https://wiki.teamfortress.com/w/images/b/b2/Backpack_Mann_Co._Supply_Crate.png",
        type: "Herramienta",
        price: 50,
        description: "Necesitas una llave de Cofre de Suministros de Mann Co. para abrirla.",
        stock: 10,
        use: 1,
        categoryId: 1,
        initial: 1,
    },
    {
        id: 3,
        name: "Series de Cofres De Suministros Mann Co. #2",
        img: "https://wiki.teamfortress.com/w/images/b/b2/Backpack_Mann_Co._Supply_Crate.png",
        type: "Herramienta",
        price: 50,
        description: "Necesitas una llave de Cofre de Suministros de Mann Co. para abrirla.",
        stock: 10,
        use: 1,
        categoryId: 1,
        initial: 1,
    },
    {
        id: 4,
        name: "Llave de Cofre Festivo de Mann Co.",
        img: "https://wiki.teamfortress.com/w/images/c/c7/Backpack_Festive_Winter_Crate_Key.png",
        type: "Herramienta",
        price: 160,
        description: "Se usa para abrir Cofres Navideños cerradas.",
        stock: 10,
        use: 1,
        categoryId: 2,
        initial: 1,
    },
    {
        id: 5,
        name: "Series de Cofre Festivo Mann Co. #1",
        img: "https://wiki.teamfortress.com/w/images/f/fc/Backpack_Festive_Winter_Crate.png",
        type: "Herramienta",
        price: 80,
        description: "Necesitas una Llave de Cofres Navideños de Mann Co. para abrirla.",
        stock: 10,
        use: 1,
        categoryId: 2,
        initial: 1,
    },
    {
        id: 6,
        name: "Series de Cofre Festivo Mann Co. #2",
        img: "https://wiki.teamfortress.com/w/images/f/fc/Backpack_Festive_Winter_Crate.png",
        type: "Herramienta",
        price: 80,
        description: "Necesitas una Llave de Cofres Navideños de Mann Co. para abrirla.",
        stock: 10,
        use: 1,
        categoryId: 2,
        initial: 1,
    },
    {
        id: 7,
        name: "Llave de Cofre Inquietante de Mann Co.",
        img: "https://wiki.teamfortress.com/w/images/a/af/Backpack_Eerie_Key.png",
        type: "Herramienta",
        price: 120,
        description: "Se usa para abrir Cofres Inquietantes cerradas.",
        stock: 10,
        use: 1,
        categoryId: 3,
        initial: 1,
    },
    {
        id: 8,
        name: "Series de Cofre Inquietante Mann Co. #1",
        img: "https://wiki.teamfortress.com/w/images/4/4b/Backpack_Eerie_Crate.png",
        type: "Herramienta",
        price: 60,
        description: "Necesitas una Llave de Cofres Inquietante de Mann Co. para abrirla.",
        stock: 10,
        use: 1,
        categoryId: 3,
        initial: 1,
    },
    {
        id: 9,
        name: "Series de Cofre Inquietante Mann Co. #2",
        img: "https://wiki.teamfortress.com/w/images/4/4b/Backpack_Eerie_Crate.png",
        type: "Herramienta",
        price: 60,
        description: "Necesitas una Llave de Cofres Inquietante de Mann Co. para abrirla.",
        stock: 10,
        use: 1,
        categoryId: 3,
        initial: 1,
    }
]

export default dataProducts